version: '3.8'

services:
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
  # client:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - influxdb
volumes:
  influxdb-storage:
